### ISSUE TITLE
Cota is not properly recognized

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#506]
Visit https://explorer.nervos.org/nft-collections/8900

There are a lot of mint transactions
<img width="1377" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/5abd2781-e15e-4bf6-8055-afd9241985b7">

1. https://explorer.nervos.org/transaction/0x7a21dc6e91d6bec48b1bdf81f6a41e2758f562a8b095a6e0b55fc0aa6c0541c4
2. https://explorer.nervos.org/transaction/0xdb3ec1ea64c59985212fde4b914214cd2ba8df7baa3404a10f7c48f842291160
3. https://explorer.nervos.org/transaction/0x2b53e4ed09707eb98d99aae8fa0ccadbbb8497b146b33412b5d3b8fb78568848
4. https://explorer.nervos.org/transaction/0x822cbda08fb8fc1ff2cc965494d097f972055931b67a360082b4d73b91cf1898

3, and 4 are not recognized as COTA transactions
<img width="1299" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/2983ce0d-cd0e-402a-bb46-622eacbae047">

<img width="1294" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/0a3d5338-bdb3-43c8-b2d2-25a59e6838de">

**Comment by FrederLu** [comment]
<img width="1306" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/0ed9d363-8940-4bce-8ab1-fc295c9e8464">
<img width="1289" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/82ae562e-feaf-46b0-bf03-8c8ffcffe413">

Their `cell_type` information in the API is different.

**Comment by rabbitz** [comment]
After checks, both `cell_type` for 3 and 4 should be `cota_regular`.
The data is a bit outdated; the node processor now correctly handles the `cell_type`.

**Comment by rabbitz** [comment]
The `cell_type` for 3 and 4 has been fixed.

**Comment by FrederLu** [comment]
> The `cell_type` for 3 and 4 has been fixed.
> 
> The erroneous data for `cota_registry` is:
> 
> ```ruby
> total count: 141
> max datetime: 2023-07-01 08:03:40 +0800
> min datetime: 2022-10-29 02:34:17 +0800
> ```

https://explorer.nervos.org/nft-collections/8900
<img width="1221" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/e37eb20e-ee26-41b3-a6a3-f8a8406100a8">

The transaction page data starting from `id:298` still exists and is not recognized as Cota.
https://explorer.nervos.org/transaction/0x394996f4321857787a0504bbf67a156a2ef30cb05e326b931b1c0dda8ee3a228
<img width="1247" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/39e73620-b111-411a-8a4e-d54fd163f80f">

**Comment by FrederLu** [comment]
Verified.
