### ISSUE TITLE
UI issues on Mobile layout

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#881]
1. style of tabs

![Image](https://github.com/user-attachments/assets/ccd998d5-f2fc-4c98-9e9a-9e212133f8c9)

2. layout

![Image](https://github.com/user-attachments/assets/ce74b527-0e58-407e-9158-68c079f49121)

![Image](https://github.com/user-attachments/assets/793805db-804f-4890-850c-ee235b1fb469)

![Image](https://github.com/user-attachments/assets/dfc79dea-2c89-4f9c-8733-a2709bd1df7a)

3. highlighted address not decent on mobile layout

![Image](https://github.com/user-attachments/assets/72d781d8-105a-4108-8448-52457e53c5f3)

These are online issues and could be fixed quickly, please prioritize this

**Comment by Keith-CY** [comment]
> 1. The cube animation is invisible on mobile
> 
> ![Image](https://github.com/user-attachments/assets/30369e73-9292-4fd4-984c-96317cdfe42d)
> 
> 2. White padding on the right due to overflow
> 
> ![Image](https://github.com/user-attachments/assets/e3159575-edd1-4430-8358-c33802ef01d6)

The 3d cube is also invisible on pc layout so I fixed it by https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1991

**Comment by Keith-CY** [comment]
This issue is past its expected completion date (2025-06-27). 
- Expected done date: 2025-06-27
- Iteration end date: 2025-07-14

Please either:
1. Move it out of the current iteration if it's no longer a priority
2. Update the expected completion date if it's still important
3. Take immediate action to complete it

@Magickbase/pm Please review and decide on the next steps.

**Comment by PainterPuppets** [comment]
> This issue is past its expected completion date (2025-06-27).
> 
> * Expected done date: 2025-06-27
> * Iteration end date: 2025-07-14
> 
> Please either:
> 
> 1. Move it out of the current iteration if it's no longer a priority
> 2. Update the expected completion date if it's still important
> 3. Take immediate action to complete it
> 
> [@Magickbase/pm](https://github.com/orgs/Magickbase/teams/pm) Please review and decide on the next steps.

fixed by https://github.com/Magickbase/ckb-explorer-frontend/pull/504

**Comment by FrederLu** [comment]
<img width="653" alt="Image" src="https://github.com/user-attachments/assets/ca1ec334-b919-44f7-a7ae-9661b7ff573b" />

<img width="309" alt="Image" src="https://github.com/user-attachments/assets/5afd479c-ee73-4510-b34d-24199600705d" />

The page adaptation problem still exists, and it is easy to appear when the page is slightly swiped left or right. At the same time, there is a slight overlap in the `SECONDS` text, which can also be dealt with.  @PainterPuppets

**Comment by Keith-CY** [comment]
This issue is past its expected completion date (2025-06-30). 
- Expected done date: 2025-06-30
- Iteration end date: 2025-07-14

Please either:
1. Move it out of the current iteration if it's no longer a priority
2. Update the expected completion date if it's still important
3. Take immediate action to complete it

@Magickbase/pm Please review and decide on the next steps.

**Comment by Keith-CY** [comment]
This issue is past its expected completion date (2025-06-30). 
- Expected done date: 2025-06-30
- Iteration end date: 2025-07-14

Please either:
1. Move it out of the current iteration if it's no longer a priority
2. Update the expected completion date if it's still important
3. Take immediate action to complete it

@Magickbase/pm Please review and decide on the next steps.
